### ISSUE TITLE
[paper abstract] Small details.

### ISSUE THREAD

**Issue by lrnv** [anselmhudde/greeks#10]
1) The first sentence of the abstract "greeks is an R package for ...." is a little hard to read and could be replaced by "The greeks R package leverages XXXX models to do XXX". It would be a lot clearer. 

2) As a second sentence you may need to give groader details about the field : people reading abstract are not from finance. Something like "These models are standard in the field of ...., they are used by <some people> to do <some easy thing to understand>. 

3) Put the shiny app sentence at the end of the abstract as a cherry on top ;)

**Comment by ahudde** [comment]
Dear @lrnv, good point. I tried to improve the abstract. Is this detailed enough? Best, Anselm

**Comment by lrnv** [comment]
Yep it's better, thank you :)
