### ISSUE TITLE
[paper] Standard refs seems lacking a bit.

### ISSUE THREAD

**Issue by lrnv** [anselmhudde/greeks#11]
The paper is well-written, GG. You make your point that your software provides functionalities that are not availiable elswewhere, and that it has been proven usefull by use in e.g. teaching. 

I find the refence section a bit lacking, you could add refs to BS, to Jumps difusion models, to standard documentations in the field that describe financial tools you are princing (like asian options) ?

**Comment by ahudde** [comment]
The merge the remainder of #18 with this #11, I add the following remarks:

    "greeks is also suited for financial risk management purposes".
    Please cite the appropriate source here or provide evidence to such claims.

    More related works are needed, especially on Asian option greeks calculations

    Yu, C. and Wang, X., 2023. Quasi-Monte Carlo-based conditional Malliavin method for continuous-time Asian option greeks. Computational Economics, 62(1), pp.325-360.
    Willems, S., 2019. Asian option pricing with orthogonal polynomials. Quantitative Finance, 19(4), pp.605-618.
    Lyuu, Y.D., Teng, H.W., Tseng, Y.T. and Wang, S.X., 2019. A systematic and efficient simulation scheme for the Greeks of financial derivatives. Quantitative Finance, 19(7), pp.1199-1219.
    and how to visualize and interact with computational tools:
    Barchart: https://www.barchart.com/options/options-calculator
    coggit: http://www.coggit.com/tools/american_option_pricing.html
    Options Calculator: https://www.optionseducation.org/toolsoptionquotes/optionscalculator

**Comment by ahudde** [comment]
Dear @bahung,
Concerning the online sources, I have some questions. In the review of existing tool for option calcuation, I mainly concentrated on tools that are on CRAN, and I also cited the to my knowledge best-known Excel-Add-in. How much a of more general review of option price calculation do we need? There are many online-tools, but you usually cannot run them on your own computer. Is then in the scope of Open Source Software?

**Comment by ahudde** [comment]
Dear @lrnv, dear @bahung,
I added some references which describe the models and fincial tools which I use in the package. Does this suffice for you?
Yours, Anselm

**Comment by lrnv** [comment]
For me looks good, dunno about the other merged issue btw, @bahung you have it.

**Comment by bahung** [comment]
For me. it also looks good! @ahudde @lrnv

**Comment by ahudde** [comment]
Thank you very much!
