### ISSUE TITLE
[paper] Expand first paragraph

### ISSUE THREAD

**Issue by lrnv** [anselmhudde/greeks#12]
The first paragraph of the statement of needs is very well written and precise in its wording. However, it is a bit short for persons that are not accointed to the field to understand what is happening. 

Between the two sentences, you might add a third one starting by "For exemple, ..." to give an exemple of a interesting sensitivity and why it is so.

**Comment by ahudde** [comment]
Dear, @lrnv, what do you think of this explanation?

**Comment by lrnv** [comment]
Perfect !
