### ISSUE TITLE
[paper] Stop bragging about your shiny app

### ISSUE THREAD

**Issue by lrnv** [anselmhudde/greeks#13]
"It includes a shiny app to interactively plot the result"

"an interactive visualisation tool is still missing [in other tools]"

"no interactive visualisation tool is provided"

"both without visualisations"

"with included interactive visualisation in a shiny app"

"greeks interactive visualisation"

A bit much dont you think ? ;)

**Comment by ahudde** [comment]
Dear @lrnv,
Thank you very much for your help. I'm bragging a little bit less. What do you think, still too much? :-)

**Comment by lrnv** [comment]
Yes that is better. Rest assured that I was joking and not aggressive at all, even if the wording can look a bit harsh.

**Comment by ahudde** [comment]
Don't worry, I was bragging too much. :-)
