### ISSUE TITLE
[internals] File greeks/src /BS_European_Greek_cpp.cpp ?

### ISSUE THREAD

**Issue by lrnv** [anselmhudde/greeks#14]
This file is full of commented code. Why ? If this code has nothing to do here, simply remlove it (it still lives in your git history it is not lost).

**Comment by ahudde** [comment]
Good point, that draft doesn't have a purpose right now, I deleted it. https://github.com/ahudde/greeks/commit/b12788d7ccafe73580adbdf78d64a64617308aab

**Comment by lrnv** [comment]
It was a draft for future functionality ? In which case it probably belongs to its own brnach so that you can work on it without having to comment / uncomment it when you make releases.

**Comment by ahudde** [comment]
That's true, I should do that. In this case, I don't think I will pursue this.
