### ISSUE TITLE
[test coverage] Add test coverage tool

### ISSUE THREAD

**Issue by lrnv** [anselmhudde/greeks#15]
Taking a look at the length of files in your R folder, I worry that your test suite is not covering all cases... 

Could you please add a test coverage Github actions workflow to the repository so that we can see clearly what is being tested or not ? It is quite easy to do, take a look there :  https://covr.r-lib.org/ 

This tool could also be helpfull for yourself, to know which part of the code you need to construct new tests for (on one hand) and to know which part of the code you can / connot trust (on the other hand).

**Comment by ahudde** [comment]
Thank you. I worked on covr myself before, but now everyone can see the results. Solved with commit https://github.com/ahudde/greeks/commit/341f43eb58e4dfdb573da5047791afea7a4c6f89

**Comment by lrnv** [comment]
Thanks ! I'll add a followup on testing then
