### ISSUE TITLE
[releases] GitHub<-> Cran inconsistency

### ISSUE THREAD

**Issue by lrnv** [anselmhudde/greeks#16]
There seem to be a lack of consistency between GitHub releases ( only one, 0.5.0, 2y ago) and CRAN releases. You might need to either make these matcheach other and create a bunch of GitHub releases (the cleanest solution IMHO) or simply remove the one you have and rely on Cran only.

**Comment by ahudde** [comment]
Thank you, that doesn't make sense. To avoid doing everything twice, I deleted the release.
