### ISSUE TITLE
[paper] general structure and comments

### ISSUE THREAD

**Issue by bahung** [anselmhudde/greeks#18]
Hi @ahudde 

Below are my comments for your paper current version:
1. Structure: Please add one section to describe the components of greeks, each with visualizations accordingly, especially when one of your paper main contributions is "Also, it is the only R package with included interactive visualization"
2. What is "Shiny app"? If it is a way to display the interactive visualizations, I think it is better to explain the mechanism to produce such visualizations and how easy to interact with them.
3. There are strong claims on the last paragraph in your statement of need section:
- "greeks is used in graduate courses in financial mathematics to provide a better understanding of option prices and Greeks by interactive visualizations." 
- "greeks is also suited for financial risk management purposes". 
Please cite the appropriate source here or provide evidence to such claims.
4. More related works are needed, especially on Asian option greeks calculations
- Yu, C. and Wang, X., 2023. Quasi-Monte Carlo-based conditional Malliavin method for continuous-time Asian option greeks. Computational Economics, 62(1), pp.325-360.
- Willems, S., 2019. Asian option pricing with orthogonal polynomials. Quantitative Finance, 19(4), pp.605-618.
- Lyuu, Y.D., Teng, H.W., Tseng, Y.T. and Wang, S.X., 2019. A systematic and efficient simulation scheme for the Greeks of financial derivatives. Quantitative Finance, 19(7), pp.1199-1219.
 and how to visualize and interact with computational tools:
- Barchart: https://www.barchart.com/options/options-calculator
- coggit: http://www.coggit.com/tools/american_option_pricing.html
- Options Calculator: https://www.optionseducation.org/toolsoptionquotes/optionscalculator

Bests

**Comment by ahudde** [comment]
Dear @bahung,

Thank you very much for your comments! 

1. and 2.: Shiny is a framework to program interactive apps, see https://shiny.posit.co/ for more information. The packages `greeks` comes with one shiny app. After you have installed the package, you can run it with `greeks::Greeks_UI()` (see also the description on readme.md). The app should be quite intuitively to operate, please try it yourself.

**Comment by ahudde** [comment]
3.1:. I am a professor of Data Science and use this package in my graduate course in financial mathematics.

**Comment by ahudde** [comment]
3.2. and 4.: I think that this belongs to Issue #11: I need more references which describe the methods that are implemented in `greeks` Also I should mention a source that describes, how the computation of Greeks is applied in risk management. I will update #11 with this point and work on this.

**Comment by bahung** [comment]
Hi @ahudde,

Thank you for your responses,
1 and 2 are for paper so that reading your paper will provide information for readers to at least imagine what they can achieve and by what steps with your app. So, please address it.

It is also related to issue #2 

3.1 it is great that the app is used wildly, kindly include a link to the course you are teaching, that I think will be a win for both sides.

That's all for the paper. I will comment for the app in other issues.

**Comment by ahudde** [comment]
Dear @bahung, 

For 1. and 2., I opened a new issue #19. I think it's better to address your points with single issues. But I will need more help from you with this issue. I will address this later.

I am currently teaching a masters course in financial mathematics of master students of applied mathematics. At our university, the course sites are restricted to students of the course. The course curriculum includes the Black Scholes Model and the computation of Greeks. We use the shiny app to get a better intuitition of options prices and greeks. Do you want to know the curriculum of the course, or what information is lacking?

**Comment by bahung** [comment]
Hi @ahudde 
I do not want it personally, what I mentioned in 3. above means that the readers of your paper or the users of your app will objectively see the benefits of using your app. So, please make the supporting evidence seen by readers/users. I also taught these courses back in 2014, and one way to provide evidence is a link to the course curriculum, such as https://platform.onlinelearning.upenn.edu/offering/finance-quantitative-modeling-for-analysts-a0Q2E00000JnjO9UAJ, and you link's content should mention Greeks.

**Comment by ahudde** [comment]
Dear @bahung, 

Thank you very much for the idea to link the course description! I added the link (see [9c3de72](https://github.com/ahudde/greeks/commit/9c3de7223137d231ab44297cd4b0ad5ba43a3b02)). The course description mentions Risk-neutral valuation, the Black Scholes Model, and hedging. This of course includes option valuation and Delta-hedging, which use the Greek Delta. But we also covered other Greeks in the course.

**Comment by ahudde** [comment]
Dear @bahung,
Does this satisfy point 3 for you?
With best regards,
Anselm

**Comment by bahung** [comment]
Hi @ahudde,

With "greeks is used in graduate courses in financial mathematics to provide a better understanding of option prices and Greeks by interactive visualizations." and the page at the link you provided https://www.hs-koblenz.de/fileadmin/media/fb_mathematik-und-technik/Pruefungsamt-Dokumente/Modulhandbuch_Ma-AM_aktuell.pdf#page=32, it seems there is no explicitly mention about your greeks software being used to calculate Greeks. If it is not possible to provide evidence to such claim, please consider rewrite it to make this statement clear.

Bests

**Comment by ahudde** [comment]
@bahung : I reformulated this sentence. What do you think? Yours, Anselm
