### ISSUE TITLE
Improve description of Shiny app

### ISSUE THREAD

**Issue by ahudde** [anselmhudde/greeks#19]
Two comments from @bahung:
- Structure: Please add one section to describe the components of greeks, each with visualizations accordingly, especially when one of your paper main contributions is  "Also, it is the only R package with included interactive visualization"
- What is "Shiny app"? If it is a way to display the interactive visualizations, I think it is better to explain the mechanism to produce such visualizations and how easy to interact with them.

**Comment by ahudde** [comment]
Dear @bahung,
Please have a look at the updated the to include a description of the shiny app. 
Furthermore, I updated the reference manual [greeks.pdf](https://github.com/ahudde/greeks/blob/main/greeks.pdf), which you can find on this repository, or on cran: https://cran.r-project.org/web/packages/greeks/greeks.pdf.
What do you think of the description of the function Greeks_UI()? Is this enough? 

Yours,
Anselm

**Comment by bahung** [comment]
Hi @ahudde,

I saw the updates regarding the UI as follows:
"For performance reasons, just the Black-Scholes model is possible, and for some cases, the set of
Greeks is limited. On the y-Axis, the option value resp. the value of the greeks are displayed, for
the x-axis, several parameters like initial_price or time_to_maturity are possible." 

It would be nice if you can be more specific:
1.  Why only BS is available?
2.  For "and for some cases, the set of Greeks is limited" --> Does the set depend on the options types? If so, please mention that.

After you finish, I think you can close this issues.

Thank you for your updates,
BaHung

**Comment by ahudde** [comment]
@bahung: Thank you. I clarified this sentence.

**Comment by ahudde** [comment]
@bahung I would like to mention the reviewers in the acknoledgements. If you aggree, with what name can I address you?

**Comment by bahung** [comment]
Thanks for the updates. I do not know the policy to acknowledge the reviewers, please check with the editor. My name is Ba Hung.

**Comment by ahudde** [comment]
Dear Ba Hung, thank you very much (and please excuse my ignorance).
