### ISSUE TITLE
[readme] Guidelines for contribution. 

### ISSUE THREAD

**Issue by lrnv** [anselmhudde/greeks#3]
You should include, at least in the readme, clear guidelines for contribution. You should provide hints for people that want to either 1) contributed to the software of 2) simoply report bugs or 3) seek your support using it.

**Comment by ahudde** [comment]
Thank you. I added a paragraph stating that contributions and bug reports are very welcome, and that in these cases, or when asking for assistance, an issue is to be opened on this repository.  https://github.com/ahudde/greeks/commit/9180c8cc5561a5b81ea7e53b470788a0a741d749
