### ISSUE TITLE
 [docs] Link to CRAN and vignettes in the readme.

### ISSUE THREAD

**Issue by lrnv** [anselmhudde/greeks#4]
The readme content is basically the vignette content, If I am right. This is not an issue, but if you could link the vignette and the reference manual that are on CRAN on the readme that would improve discoverability.

**Comment by ahudde** [comment]
Dear @lrnv, is this what you suggested? https://github.com/ahudde/greeks/commit/bdf6235d59ffc3fddc4e686241d15052c8317ad0

**Comment by lrnv** [comment]
Yes indeed, that is better thank you :) Note that refereing issues numbers in commit messages links them directly, no need to copy the comit hashes in comments :).
