### ISSUE TITLE
[docs] Lacking content, description of context and references

### ISSUE THREAD

**Issue by lrnv** [anselmhudde/greeks#5]
The documentations of the different functions are a bit lacking... In particular, the "Details" sections, the "Value" section, that are supposed to give an overview of what the function will do / does. Without asking too much of you, maybe you could include the mathematical definitions of the objects that your functions are computing and a few references to the corresponding litterature ? 

As an exemple, let's take the `Greeks` function documentation: 

````
Description : Computes the Greeks of various options
Value : Named vector containing the values of the Greeks specified in the parameter greek.
````

The description field could include a discussion of : 
- What are the greeks ? Give a broad overview and link to the litterature for more details, this will be enough : " "Greeks are derivative of the value function of assets, usually used for blablabla...". You may even link wikipedia !
- Under which model / assumptions your code works ? 
- All that with references to the litterature. IIRC there is the possiiblity to cite the litterature in R docs. 

Same remark for all functions... One possibility is to have this done in a "master function" and then link the other ones to it via "See also links".

Idea: Take the references from the joss paper, they seem great !

**Comment by ahudde** [comment]
Dear @lrnv : I worked on the description field of the function `Greeks`. See the file `greeks.pdf` for the resulting reference manual. Is this going in the right direction? Yours, Anselm

**Comment by lrnv** [comment]
Yes, the description of the Greeks function is definitely better, great job. There are still functions without much description though, so you have to either complete their descriptions either refer to other parts of the docs that do (like the now-very-descriptive Greeks docs)

**Comment by ahudde** [comment]
Great, thanks for the feedback, I will work on the other functions, too.

**Comment by ahudde** [comment]
Dear @lrnv, how do you like the documentation now (if you could a glance, it has grown a bit :-))?

Best, Anselm

**Comment by lrnv** [comment]
From reading the commits that are referenced here, yeah this is going great.

From reading the documentation itself (the .pdf) it looks a lot better. Great job @ahudde :)

You can close this ticket

**Comment by ahudde** [comment]
Thank you very much!
