### ISSUE TITLE
[docs] Internal references of your docs

### ISSUE THREAD

**Issue by lrnv** [anselmhudde/greeks#7]
Your documentation does not link with itself enough for discoverability of your functions. You might include on major documentation pages a see also note to provide a few others links to docuimentation of functions in your package that are relevant to this function.

**Comment by ahudde** [comment]
Dear @lrnv,
Thanks, that is a good point. I added the relevant seealso-notes. What do you think?

Best,
Anselm

**Comment by lrnv** [comment]
Yep this is what I intended !

**Comment by ahudde** [comment]
Great, thanks!
