### ISSUE TITLE
[vignette] Picture too big

### ISSUE THREAD

**Issue by lrnv** [anselmhudde/greeks#8]
The picture in the vignette is waaaaay too big. Maybe you could do something so that it auto-scales ?

**Comment by ahudde** [comment]
Good point, that was also easy to fit, see commit [5450d71.](https://github.com/ahudde/greeks/commit/5450d71abdf3e6c66653dc14bc5355716facfd4e)

**Comment by ahudde** [comment]
Please reopen, if this doesn't yet scale well enough.
